### ISSUE TITLE
Remove ACLs from files and directories

### ISSUE THREAD

**Issue by kylesimmonds** [sindresorhus/gulp-chmod#10]
I have a few files downloaded from Dropbox that have extended attributes set, also called Access Control Lists in macOS. Is there a way using this plugin to modify or remove extended attributes, or is it limited to user/group/world only?

Here's the options I use to remove ACLs: `chmod -RN`

**Comment by sindresorhus** [comment]
Not possible as Gulp itself only support POSIX permissions.

**Comment by kylesimmonds** [comment]
Gotcha, thanks!

**Comment by sindresorhus** [comment]
You can either open an issue on Gulp about adding it there, or process the files with `chmod -RN` using for example [`execa`](https://github.com/sindresorhus/execa) after running them through a Gulp pipeline.

**Comment by kylesimmonds** [comment]
I actually opted to use gulp-shell to run the commands natively:

```
.pipe(shell([
  'chmod -RN <%= file.path %>',
  'chmod 755 <%= file.path %>'
]))
```
