### ISSUE TITLE
Folder is not copied if folder mode is present

### ISSUE THREAD

**Issue by lucomsky** [sindresorhus/gulp-chmod#13]
[explanation.tar.gz](https://github.com/sindresorhus/gulp-chmod/files/1625617/explanation.tar.gz)

gulp-chmod version 2.0.0 from npm.

This gulpfile.js doesn't work for me if I have folders in src :-(.

const gulp = require('gulp');
const chmod = require('gulp-chmod');

gulp.task('default', () =>
        gulp.src('src/*')
                .pipe(chmod(0o755, 0o755))
                .pipe(gulp.dest('dist'))
);

**Comment by sindresorhus** [comment]
Submit a pull request with a [failing test](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#failing-tests) and I'll take a closer look. I'm requesting this as most issues like these are just users using the module incorrectly or an unrelated problem.
