### ISSUE TITLE
The plugin does not change the attributes

### ISSUE THREAD

**Issue by Korneffstyle** [sindresorhus/gulp-chmod#16]
Hi, I use Gulp for development in Visual Studio, which puts the "read-only" attribute on all files in the project.

I need to clear the "read only" attribute when running Gulp.

The plugin was installed correctly, the task is written, but the attribute is not removed.

**Comment by sindresorhus** [comment]
Submit a pull request with a [failing test](https://github.com/avajs/ava#failing-tests) and I'll take a closer look. I'm requesting this as most issues like these are just users using the module incorrectly or an unrelated problem.
