### ISSUE TITLE
`dirMode` option

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/gulp-chmod#6]
From #4 

> I think this should follow gulp.dest and have a separate option for dirMode as it seems that's needed for some reason: wearefractal/vinyl-fs#35 Could maybe have it as a second argument to chmod.

**Comment by icd2k3** [comment]
+1 for this!

My use case: using `sudo gulp` to launch localhost on port 80, creates a .tmp folder of compiled scss and templates, would be nice to be able to remove that directory later in a different task without having to use sudo.

**Comment by jjmartin** [comment]
I'm interested in seeing this too as a fix  for the issue i had in gulp zip.  https://github.com/sindresorhus/gulp-zip/issues/64

looking in to the dirMode option you want for a pull request

**Comment by clintharris** [comment]
+1

**Comment by pesek** [comment]
+1

**Comment by northerncodemky** [comment]
+1

**Comment by sindresorhus** [comment]
PR welcome :)

**Comment by jbsulli** [comment]
Check out my pull request #8. I just made a simple flag that you could pass true to have the mode be applied to folders as well. Could be expanded to support an entirely different mode for directories without much work.

**Comment by sindresorhus** [comment]
FIxed by https://github.com/sindresorhus/gulp-chmod/pull/8.
