### ISSUE TITLE
New octal integer literal 

### ISSUE THREAD

**Issue by zevero** [sindresorhus/gulp-chmod#9]
Ok so today I learned that with updating to 2.0.0 I need to use new octal integer literals.
  
     .pipe(chmod(0o777))

It would be very kind of you to add some warning, when still using the old syntax ... as it would shorten the time to fix update errors considerably!

Thank you!

**Comment by sindresorhus** [comment]
It's was a major release. You shouldn't just update without checking for breaking changes. Wouldn't be possible detect as the octal literal is just syntactic.

**Comment by zevero** [comment]
Does a value above 0o777 (that is 511) make sense?
